# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homilienote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homilinotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homilienote',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_homilinotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lectiodivinasession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectio_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingplanpassage',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_passages', to='bible.readingplan'),
        ),
        migrations.AddField(
            model_name='readingplansubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='bible.readingplan'),
        ),
        migrations.AddField(
            model_name='readingplansubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_plan_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='testament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='bible.testament'),
        ),
        migrations.AddField(
            model_name='verse',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.chapter'),
        ),
        migrations.AddField(
            model_name='readingplanpassage',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_passages', to='bible.verse'),
        ),
        migrations.AddField(
            model_name='lectiodivinasession',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectio_sessions', to='bible.verse'),
        ),
        migrations.AddField(
            model_name='homilienote',
            name='passage_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homilinote_ends', to='bible.verse'),
        ),
        migrations.AddField(
            model_name='homilienote',
            name='passage_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homilinote_starts', to='bible.verse'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('book', 'number')},
        ),
        migrations.AddConstraint(
            model_name='readingplansubscription',
            constraint=models.UniqueConstraint(fields=('user', 'plan'), name='uniq_reading_plan_subscription'),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv'], name='idx_verse_tsv'),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_verse_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('chapter', 'number', 'source_file')},
        ),
        migrations.AddConstraint(
            model_name='lectiodivinasession',
            constraint=models.UniqueConstraint(condition=models.Q(('passage__isnull', False)), fields=('user', 'passage'), name='uniq_lectio_user_passage'),
        ),
        migrations.AddConstraint(
            model_name='lectiodivinasession',
            constraint=models.UniqueConstraint(condition=models.Q(('passage__isnull', True)), fields=('user', 'session_date'), name='uniq_lectio_user_day_without_passage'),
        ),
    ]
