# Generated by Django 5.2.16 on 2026-09-27 16:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0003_search_trigram"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParolePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("personnalisation_parole", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parole_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglages de la Parole",
                "verbose_name_plural": "Réglages de la Parole",
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Aucune (signet)"),
                            ("jaune", "Jaune"),
                            ("vert", "Vert"),
                            ("bleu", "Bleu"),
                            ("rose", "Rose"),
                            ("violet", "Violet"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="bible.verse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signet",
                "verbose_name_plural": "Signets",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "verse"), name="uniq_bookmark_user_verse"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("payload", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation du jour",
                "verbose_name_plural": "Recommandations du jour",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="uniq_daily_reco_user_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReadingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_event_id", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lu", "Lu"),
                            ("signet", "Signet"),
                            ("surligne", "Surligné"),
                            ("recherche", "Ouvert depuis une recherche"),
                            ("lectio", "Lectio divina"),
                        ],
                        max_length=16,
                    ),
                ),
                ("finished", models.BooleanField(default=False)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_events",
                        to="bible.chapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verse_end",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_events_end",
                        to="bible.verse",
                    ),
                ),
                (
                    "verse_start",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_events_start",
                        to="bible.verse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signal de lecture",
                "verbose_name_plural": "Signaux de lecture",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-occurred_at"],
                        name="idx_reading_event_user_time",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_event_id"),
                        name="uniq_reading_event_client_id",
                    )
                ],
            },
        ),
    ]
