# Generated by Django 5.2.16 on 2026-09-29 17:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hierarchy", "0014_v1_routes_capacites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MassIntention",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("defunt", "Pour un défunt"),
                            ("action_de_graces", "Action de grâces"),
                            ("particuliere", "Intention particulière"),
                        ],
                        max_length=20,
                        verbose_name="nature",
                    ),
                ),
                (
                    "intention",
                    models.CharField(max_length=500, verbose_name="intention"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="sans mon nom"),
                ),
                ("requested_date", models.DateField(verbose_name="date souhaitée")),
                (
                    "requested_mass",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="messe souhaitée",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recue", "Reçue"),
                            ("planifiee", "Planifiée"),
                            ("refusee", "Refusée"),
                            ("celebree", "Célébrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="recue",
                        max_length=12,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date retenue"
                    ),
                ),
                (
                    "scheduled_mass",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="messe retenue",
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "refusal_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="motif du refus",
                    ),
                ),
                ("celebrated_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mass_intentions",
                        to="hierarchy.node",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hierarchy.placeofworship",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mass_intentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "intention de messe",
                "verbose_name_plural": "intentions de messe",
                "ordering": ["requested_date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["node", "status", "requested_date"],
                        name="intention_node_status_idx",
                    ),
                    models.Index(
                        fields=["requester", "-created_at"],
                        name="intention_requester_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "planifiee"), _negated=True),
                            ("scheduled_date__isnull", False),
                            _connector="OR",
                        ),
                        name="intention_scheduled_has_date",
                    )
                ],
            },
        ),
    ]
