# Generated by Django 5.2.16 on 2026-09-29 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0014_v1_routes_capacites"),
        ("intentions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="massintention",
            name="scheduled_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="heure de la messe retenue"
            ),
        ),
        migrations.AlterField(
            model_name="massintention",
            name="requested_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="date souhaitée"
            ),
        ),
        migrations.CreateModel(
            name="IntentionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_per_mass",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="intentions par messe au plus"
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intention_settings",
                        to="hierarchy.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "réglages des intentions",
                "verbose_name_plural": "réglages des intentions",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_per_mass__gte", 1), ("max_per_mass__lte", 50)
                        ),
                        name="intention_settings_max_range",
                    )
                ],
            },
        ),
    ]
