# Generated by Django 5.2.16 on 2026-09-29 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0014_v1_routes_capacites"),
        ("intentions", "0002_v1_complements"),
    ]

    operations = [
        migrations.CreateModel(
            name="MassCapOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.TimeField(verbose_name="heure")),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="jour (0 = lundi)"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "max_intentions",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="intentions au plus"
                    ),
                ),
            ],
            options={
                "verbose_name": "plafond d'une messe",
                "verbose_name_plural": "plafonds des messes",
            },
        ),
        migrations.RemoveConstraint(
            model_name="intentionsettings",
            name="intention_settings_max_range",
        ),
        migrations.AlterField(
            model_name="intentionsettings",
            name="max_per_mass",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=5,
                null=True,
                verbose_name="intentions par messe au plus",
            ),
        ),
        migrations.AddConstraint(
            model_name="intentionsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_per_mass__isnull", True),
                    models.Q(("max_per_mass__gte", 1), ("max_per_mass__lte", 50)),
                    _connector="OR",
                ),
                name="intention_settings_max_range",
            ),
        ),
        migrations.AddField(
            model_name="masscapoverride",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mass_cap_overrides",
                to="hierarchy.node",
            ),
        ),
        migrations.AddField(
            model_name="masscapoverride",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mass_cap_overrides",
                to="hierarchy.placeofworship",
            ),
        ),
        migrations.AddConstraint(
            model_name="masscapoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("weekday__isnull", True), ("date__isnull", False)),
                    models.Q(
                        ("weekday__isnull", False),
                        ("date__isnull", True),
                        ("weekday__lte", 6),
                    ),
                    _connector="OR",
                ),
                name="mass_cap_weekday_xor_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="masscapoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_intentions__isnull", True),
                    models.Q(("max_intentions__gte", 1), ("max_intentions__lte", 50)),
                    _connector="OR",
                ),
                name="mass_cap_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="masscapoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date__isnull", True)),
                fields=("place", "weekday", "start_time"),
                name="mass_cap_unique_weekly",
            ),
        ),
        migrations.AddConstraint(
            model_name="masscapoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date__isnull", False)),
                fields=("place", "date", "start_time"),
                name="mass_cap_unique_dated",
            ),
        ),
    ]
