# Generated by Django 5.2.16 on 2026-09-29 17:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hierarchy", "0014_v1_routes_capacites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClergyInvitation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="prénom"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="nom"
                    ),
                ),
                (
                    "etat_de_vie",
                    models.CharField(
                        choices=[
                            ("laic", "Laïc"),
                            ("clerc", "Clerc"),
                            ("consacre", "Consacré"),
                        ],
                        max_length=10,
                        verbose_name="état de vie",
                    ),
                ),
                (
                    "degre_ordre",
                    models.CharField(
                        choices=[
                            ("aucun", "Aucun"),
                            ("diacre_transitoire", "Diacre (transitoire)"),
                            ("diacre_permanent", "Diacre permanent"),
                            ("pretre", "Prêtre"),
                            ("eveque", "Évêque"),
                        ],
                        max_length=20,
                        verbose_name="degré d'ordre",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("revoquee", "Révoquée"),
                            ("expiree", "Expirée"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expire le")),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clergy_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clergy_invitations",
                        to="hierarchy.node",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation du clergé",
                "verbose_name_plural": "invitations du clergé",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["node", "status", "-created_at"],
                        name="invitation_node_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "en_attente")),
                        fields=("email", "node"),
                        name="invitation_one_pending_per_email_node",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("etat_de_vie", "laic"), _negated=True),
                        name="invitation_not_laic",
                    ),
                ],
            },
        ),
    ]
