# Generated by Django 5.2.16 on 2026-09-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clergyinvitation",
            name="justificatif",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="files.file",
                verbose_name="pièce justificative",
            ),
        ),
    ]
