# Generated by Django 5.2.16 on 2026-09-27 11:33

import apps.donations.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0002_initial"),
        ("hierarchy", "0009_dons_capacites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=30)),
                ("payload_hash", models.CharField(max_length=64, unique=True)),
                (
                    "external_ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "reported_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("signature_valid", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recu", "Reçu"),
                            ("traite", "Traité"),
                            ("doublon", "Doublon"),
                            ("rejete", "Rejeté (signature)"),
                            ("erreur", "Erreur de traitement"),
                        ],
                        db_index=True,
                        default="recu",
                        max_length=10,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=60)),
                (
                    "payload",
                    apps.donations.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "notification de paiement",
                "verbose_name_plural": "notifications de paiement",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="CashCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mass_date", models.DateField(verbose_name="date de la messe")),
                ("mass_label", models.CharField(max_length=120, verbose_name="messe")),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="montant compté (FCFA)"),
                ),
                (
                    "counter_one",
                    models.CharField(max_length=120, verbose_name="premier compteur"),
                ),
                (
                    "counter_two",
                    models.CharField(max_length=120, verbose_name="second compteur"),
                ),
                (
                    "observation",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="observation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("saisie", "Saisie, à valider"),
                            ("validee", "Validée"),
                            ("rejetee", "Rejetée"),
                        ],
                        db_index=True,
                        default="saisie",
                        max_length=10,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_collections",
                        to="hierarchy.node",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hierarchy.placeofworship",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "quête en espèces",
                "verbose_name_plural": "quêtes en espèces",
                "ordering": ["-mass_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=20, unique=True)),
                ("amount", models.PositiveIntegerField(verbose_name="don (FCFA)")),
                (
                    "fees_covered",
                    models.BooleanField(
                        default=False, verbose_name="frais couverts par le donateur"
                    ),
                ),
                (
                    "fee_amount",
                    models.PositiveIntegerField(default=0, verbose_name="frais (FCFA)"),
                ),
                (
                    "charged_amount",
                    models.PositiveIntegerField(verbose_name="montant payé (FCFA)"),
                ),
                (
                    "net_amount",
                    models.PositiveIntegerField(
                        verbose_name="montant affecté au fonds (FCFA)"
                    ),
                ),
                (
                    "anonymous",
                    models.BooleanField(default=False, verbose_name="don anonyme"),
                ),
                (
                    "donor_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("en_ligne", "En ligne"), ("especes", "Espèces")],
                        default="en_ligne",
                        max_length=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wave", "Wave"),
                            ("orange_money", "Orange Money"),
                            ("free_money", "Free Money"),
                            ("carte", "Carte bancaire"),
                            ("especes", "Espèces"),
                            ("autre", "Autre"),
                            ("inconnu", "Inconnu"),
                        ],
                        default="inconnu",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initie", "Initié"),
                            ("en_attente", "En attente de confirmation"),
                            ("confirme", "Confirmé"),
                            ("echoue", "Échoué"),
                            ("expire", "Expiré"),
                            ("rembourse", "Remboursé"),
                        ],
                        db_index=True,
                        default="initie",
                        max_length=12,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("receipt_email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cash_collection",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donation",
                        to="donations.cashcollection",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "don",
                "verbose_name_plural": "dons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="collecte active"),
                ),
                (
                    "authorization_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="référence de l'autorisation",
                    ),
                ),
                (
                    "authorization_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de l'autorisation"
                    ),
                ),
                (
                    "authorization_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex. « Collecte autorisée par l'Archevêché de Dakar (réf. …) ». Vide : texte par défaut.",
                        max_length=300,
                        verbose_name="mention affichée",
                    ),
                ),
                (
                    "allocation_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="clé d'affectation",
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_activation",
                        to="hierarchy.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "activation des dons",
                "verbose_name_plural": "activations des dons",
            },
        ),
        migrations.CreateModel(
            name="DonationStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("initie", "Initié"),
                            ("en_attente", "En attente de confirmation"),
                            ("confirme", "Confirmé"),
                            ("echoue", "Échoué"),
                            ("expire", "Expiré"),
                            ("rembourse", "Remboursé"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("initie", "Initié"),
                            ("en_attente", "En attente de confirmation"),
                            ("confirme", "Confirmé"),
                            ("echoue", "Échoué"),
                            ("expire", "Expiré"),
                            ("rembourse", "Remboursé"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("checkout", "Création du paiement"),
                            ("webhook", "Notification de l'agrégateur"),
                            ("reconciliation", "Réconciliation"),
                            ("staff", "Action du staff"),
                            ("system", "Système"),
                        ],
                        max_length=15,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="donations.donation",
                    ),
                ),
            ],
            options={
                "verbose_name": "changement de statut d'un don",
                "verbose_name_plural": "changements de statut des dons",
                "ordering": ["at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("quete_dominicale", "Quête dominicale"),
                            ("quete_imperee", "Quête impérée"),
                            ("campagne", "Campagne pour un projet"),
                            ("contribution_annuelle", "Contribution annuelle"),
                        ],
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("paroisse", "Paroisse"),
                            ("curie", "Curie diocésaine"),
                        ],
                        default="paroisse",
                        max_length=10,
                        verbose_name="destination",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="titre")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="usage des fonds"
                    ),
                ),
                (
                    "starts_on",
                    models.DateField(blank=True, null=True, verbose_name="début"),
                ),
                (
                    "ends_on",
                    models.DateField(blank=True, null=True, verbose_name="fin"),
                ),
                (
                    "goal_amount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="objectif (FCFA)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("ouvert", "Ouvert"),
                            ("clos", "Clos"),
                        ],
                        db_index=True,
                        default="brouillon",
                        max_length=10,
                    ),
                ),
                (
                    "decided_by_office",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="office qui décide",
                    ),
                ),
                (
                    "authorization_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="référence de l'autorisation",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.file",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donation_funds",
                        to="hierarchy.node",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parish_funds",
                        to="donations.fund",
                    ),
                ),
            ],
            options={
                "verbose_name": "fonds",
                "verbose_name_plural": "fonds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donations",
                to="donations.fund",
            ),
        ),
        migrations.AddField(
            model_name="cashcollection",
            name="fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_collections",
                to="donations.fund",
            ),
        ),
        migrations.CreateModel(
            name="FundUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=2000, verbose_name="texte")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="donations.fund",
                    ),
                ),
            ],
            options={
                "verbose_name": "nouvelle de campagne",
                "verbose_name_plural": "nouvelles de campagne",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=30)),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("idempotency_key", models.CharField(max_length=80, unique=True)),
                (
                    "checkout_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cree", "Créé"),
                            ("en_attente", "En attente"),
                            ("reussi", "Réussi"),
                            ("echoue", "Échoué"),
                            ("annule", "Annulé"),
                            ("expire", "Expiré"),
                        ],
                        db_index=True,
                        default="cree",
                        max_length=12,
                    ),
                ),
                (
                    "raw_payload",
                    apps.donations.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="donations.donation",
                    ),
                ),
            ],
            options={
                "verbose_name": "tentative de paiement",
                "verbose_name_plural": "tentatives de paiement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=30)),
                ("external_ref", models.CharField(max_length=120)),
                ("paid_at", models.DateTimeField()),
                ("gross_amount", models.PositiveIntegerField()),
                ("fee_amount", models.PositiveIntegerField(default=0)),
                ("net_amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recu", "Reçu, à rapprocher"),
                            ("rapproche", "Rapproché"),
                            ("ecart", "Écart constaté"),
                        ],
                        db_index=True,
                        default="recu",
                        max_length=10,
                    ),
                ),
                ("discrepancy_amount", models.IntegerField(default=0)),
                ("unmatched_count", models.PositiveIntegerField(default=0)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donation_payouts",
                        to="hierarchy.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "reversement",
                "verbose_name_plural": "reversements",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="payout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="donations.payout",
            ),
        ),
        migrations.CreateModel(
            name="PayoutLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_ref", models.CharField(max_length=120)),
                ("amount", models.PositiveIntegerField()),
                ("fee_amount", models.PositiveIntegerField(default=0)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="donations.paymentattempt",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="donations.payout",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de reversement",
                "verbose_name_plural": "lignes de reversement",
            },
        ),
        migrations.AddIndex(
            model_name="fund",
            index=models.Index(
                fields=["node", "status"], name="dons_fund_node_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "quete_imperee"), _negated=True),
                    ("destination", "curie"),
                    _connector="OR",
                ),
                name="dons_fund_imperee_curie",
            ),
        ),
        migrations.AddConstraint(
            model_name="fund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_on__isnull", True),
                    ("starts_on__isnull", True),
                    ("ends_on__gte", models.F("starts_on")),
                    _connector="OR",
                ),
                name="dons_fund_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="fund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("goal_amount__isnull", True),
                    ("goal_amount__gt", 0),
                    _connector="OR",
                ),
                name="dons_fund_goal_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashcollection",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="dons_cash_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashcollection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("validated_by__isnull", True),
                    models.Q(("validated_by", models.F("entered_by")), _negated=True),
                    _connector="OR",
                ),
                name="dons_cash_four_eyes",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_ref__isnull", False)),
                fields=("provider", "external_ref"),
                name="dons_attempt_unique_external_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.UniqueConstraint(
                fields=("provider", "external_ref"), name="dons_payout_unique_ref"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["fund", "status"], name="dons_donation_fund_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["donor", "status"], name="dons_donation_donor_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="dons_donation_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                condition=models.Q(("net_amount__lte", models.F("charged_amount"))),
                name="dons_donation_net_le_charged",
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("channel", "en_ligne"),
                    ("cash_collection__isnull", False),
                    _connector="OR",
                ),
                name="dons_donation_cash_has_collection",
            ),
        ),
    ]
