# Generated by Django 5.2.16 on 2026-09-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
        ("hierarchy", "0009_dons_capacites"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="donationactivation",
            name="receipt_prefix",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="préfixe des reçus"
            ),
        ),
        migrations.CreateModel(
            name="ReceiptSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hierarchy.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "série de reçus",
                "verbose_name_plural": "séries de reçus",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("node", "year"), name="dons_receipt_sequence_unique"
                    )
                ],
            },
        ),
    ]
