"""Dons : canal d'entrée, lieu de culte, date de valeur, frais réels, retour dans l'app (expand)."""

# Generated by Django 5.2.16 on 2026-09-27 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Reprise de l'existant : date de valeur (espèces : jour de la messe ; en ligne : date locale de
    confirmation, Africa/Dakar = UTC), source « inconnu » des dons en ligne, lieu des espèces."""
    Donation = apps.get_model("donations", "Donation")
    for donation in Donation.objects.filter(value_date__isnull=True).select_related("cash_collection").iterator():
        fields = []
        if donation.cash_collection_id:
            donation.value_date = donation.cash_collection.mass_date
            donation.place_id = donation.cash_collection.place_id
            fields += ["value_date", "place"]
        else:
            donation.source = "inconnu"
            fields.append("source")
            if donation.confirmed_at:
                donation.value_date = donation.confirmed_at.date()
                fields.append("value_date")
        donation.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_numerotation_recus"),
        ("hierarchy", "0009_dons_capacites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="fee_is_actual",
            field=models.BooleanField(default=False, verbose_name="frais réels"),
        ),
        migrations.AddField(
            model_name="donation",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hierarchy.placeofworship",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("app_ios", "App iOS"),
                    ("app_android", "App Android"),
                    ("web", "Site"),
                    ("qr", "QR code"),
                    ("inconnu", "Non précisé"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="value_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="date de valeur"
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hierarchy.placeofworship",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["fund", "value_date"], name="dons_donation_fund_value_idx"
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
