# Generated by Django 5.2.16 on 2026-09-27 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_source_lieu_date_valeur"),
        ("hierarchy", "0009_dons_capacites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="remit_by",
            field=models.DateField(
                blank=True, null=True, verbose_name="à remettre à la curie avant le"
            ),
        ),
        migrations.CreateModel(
            name="CashDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deposited_on", models.DateField(verbose_name="date du dépôt")),
                (
                    "bank_label",
                    models.CharField(max_length=120, verbose_name="banque et compte"),
                ),
                (
                    "slip_number",
                    models.CharField(max_length=60, verbose_name="numéro de bordereau"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="montant déposé (FCFA)"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="observation",
                    ),
                ),
                (
                    "declared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_deposits",
                        to="hierarchy.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "dépôt d'espèces",
                "verbose_name_plural": "dépôts d'espèces",
                "ordering": ["-deposited_on", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cashcollection",
            name="deposit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collections",
                to="donations.cashdeposit",
            ),
        ),
        migrations.CreateModel(
            name="CuriaRemittance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="montant remis (FCFA)"),
                ),
                ("remitted_on", models.DateField(verbose_name="date de la remise")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces remises à la curie"),
                            ("virement", "Virement"),
                            (
                                "compensation",
                                "Compensation sur la rétrocession de l'économat",
                            ),
                        ],
                        default="especes",
                        max_length=15,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="référence (reçu de la curie, virement)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("declaree", "Déclarée par la paroisse"),
                            ("confirmee", "Réception confirmée par la curie"),
                            ("contestee", "Contestée par la curie"),
                        ],
                        db_index=True,
                        default="declaree",
                        max_length=10,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "declared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remittances",
                        to="donations.fund",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curia_remittances",
                        to="hierarchy.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "remise à la curie",
                "verbose_name_plural": "remises à la curie",
                "ordering": ["-remitted_on", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="cashdeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="dons_deposit_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashdeposit",
            constraint=models.UniqueConstraint(
                fields=("node", "slip_number"), name="dons_deposit_unique_slip"
            ),
        ),
        migrations.AddConstraint(
            model_name="curiaremittance",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="dons_remittance_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="curiaremittance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confirmed_by__isnull", True),
                    models.Q(("confirmed_by", models.F("declared_by")), _negated=True),
                    _connector="OR",
                ),
                name="dons_remittance_four_eyes",
            ),
        ),
    ]
