# Generated by Django 5.2.16 on 2026-09-27 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_depot_especes_remise_curie"),
        ("hierarchy", "0010_dons_voir_agregats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "remboursement",
                                "Remboursement (ligne négative du mois du remboursement)",
                            ),
                            ("correction", "Correction d'un mois clos"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("en_ligne", "En ligne"), ("especes", "Espèces")],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("app_ios", "App iOS"),
                            ("app_android", "App Android"),
                            ("web", "Site"),
                            ("qr", "QR code"),
                            ("inconnu", "Non précisé"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wave", "Wave"),
                            ("orange_money", "Orange Money"),
                            ("free_money", "Free Money"),
                            ("carte", "Carte bancaire"),
                            ("especes", "Espèces"),
                            ("autre", "Autre"),
                            ("inconnu", "Inconnu"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="montant donné (signé)")),
                (
                    "net_amount",
                    models.IntegerField(verbose_name="montant affecté (signé)"),
                ),
                (
                    "value_date",
                    models.DateField(db_index=True, verbose_name="date de valeur"),
                ),
                ("reason", models.CharField(max_length=300, verbose_name="motif")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="donations.donation",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="donations.fund",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donation_adjustments",
                        to="hierarchy.node",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hierarchy.placeofworship",
                    ),
                ),
            ],
            options={
                "verbose_name": "ajustement",
                "verbose_name_plural": "ajustements",
                "ordering": ["-value_date", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount", 0), _negated=True),
                        name="dons_adjustment_non_zero",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "remboursement")),
                        fields=("donation",),
                        name="dons_adjustment_one_refund",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthClosing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.DateField(verbose_name="mois (premier jour)")),
                ("totals", models.JSONField(default=dict, verbose_name="totaux figés")),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donation_closings",
                        to="hierarchy.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "clôture mensuelle",
                "verbose_name_plural": "clôtures mensuelles",
                "ordering": ["-month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("node", "month"), name="dons_closing_unique_month"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("month__day", 1)),
                        name="dons_closing_first_day",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "late_payment",
                                "Paiement réussi après expiration ou échec",
                            ),
                            (
                                "amount_mismatch",
                                "Montant payé différent du montant attendu",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ouvert", "À régulariser"), ("resolu", "Régularisé")],
                        db_index=True,
                        default="ouvert",
                        max_length=10,
                    ),
                ),
                ("reported_amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("integre", "Paiement intégré au fonds (don confirmé)"),
                            ("rembourse", "Remboursé chez l'agrégateur"),
                            ("sans_suite", "Sans suite (vérifié, rien à faire)"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="donations.paymentattempt",
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="donations.donation",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "incident de paiement",
                "verbose_name_plural": "incidents de paiement",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "kind"),
                        name="dons_incident_unique_attempt_kind",
                    )
                ],
            },
        ),
    ]
