# Generated by Django 5.2.16 on 2026-09-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0005_cloture_ajustements_incidents"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="messe_anticipee_incluse",
            field=models.BooleanField(
                default=False, verbose_name="messe anticipée incluse"
            ),
        ),
    ]
