# Generated by Django 5.2.7 on 2026-09-25 08:53

import apps.messaging.fields
import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('cgu_accepted_by_a', models.DateTimeField(blank=True, null=True)),
                ('cgu_accepted_by_b', models.DateTimeField(blank=True, null=True)),
                ('scheduled_purge_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='ConversationExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Export Conversation',
                'verbose_name_plural': 'Exports Conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', apps.messaging.fields.EncryptedTextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('text', 'Texte'), ('media', 'Média'), ('system', 'Système')], default='text', max_length=10)),
                ('client_message_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True, unique=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='MessageBlock',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Blocage',
                'verbose_name_plural': 'Blocages',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Réaction',
                'verbose_name_plural': 'Réactions',
            },
        ),
        migrations.CreateModel(
            name='MessagingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepts_new_conversations', models.BooleanField(default=True, verbose_name='accepte de nouveaux échanges')),
                ('absent_until', models.DateField(blank=True, null=True, verbose_name="absent jusqu'au")),
                ('reply_windows', models.JSONField(blank=True, default=list, verbose_name='plages de réponse')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='note')),
            ],
            options={
                'verbose_name': 'Disponibilité (messagerie)',
                'verbose_name_plural': 'Disponibilités (messagerie)',
            },
        ),
        migrations.CreateModel(
            name='MessagingCguAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Acceptation CGU messagerie',
                'verbose_name_plural': 'Acceptations CGU messagerie',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_app', models.BooleanField(default=True, verbose_name="dans l'application")),
                ('email', models.BooleanField(default=True, verbose_name='par e-mail')),
                ('topic_annonces', models.BooleanField(default=True, verbose_name='annonces de ma paroisse')),
                ('topic_evenements', models.BooleanField(default=True, verbose_name="rappels d'événements")),
                ('quiet_start', models.TimeField(default=datetime.time(22, 0), verbose_name='début du silence')),
                ('quiet_end', models.TimeField(default=datetime.time(6, 0), verbose_name='fin du silence')),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('token', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'verbose_name': 'Appareil push',
                'verbose_name_plural': 'Appareils push',
            },
        ),
    ]
