# Generated by Django 5.2.7 on 2026-09-25 03:15

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_pushdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_app', models.BooleanField(default=True, verbose_name="dans l'application")),
                ('email', models.BooleanField(default=True, verbose_name='par e-mail')),
                ('topic_annonces', models.BooleanField(default=True, verbose_name='annonces de ma paroisse')),
                ('topic_evenements', models.BooleanField(default=True, verbose_name="rappels d'événements")),
                ('quiet_start', models.TimeField(default=datetime.time(22, 0), verbose_name='début du silence')),
                ('quiet_end', models.TimeField(default=datetime.time(6, 0), verbose_name='fin du silence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
    ]
