# Generated by Django 5.2.7 on 2026-09-25 04:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_notification_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepts_new_conversations', models.BooleanField(default=True, verbose_name='accepte de nouveaux échanges')),
                ('absent_until', models.DateField(blank=True, null=True, verbose_name="absent jusqu'au")),
                ('reply_windows', models.JSONField(blank=True, default=list, verbose_name='plages de réponse')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='note')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilité (messagerie)',
                'verbose_name_plural': 'Disponibilités (messagerie)',
            },
        ),
    ]
