# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('announcement', 'Annonce'), ('article', 'Article'), ('pastoral_letter', 'Lettre Pastorale'), ('meditation', 'Méditation du jour')], db_index=True, default='article', max_length=20, verbose_name='Type de contenu')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=220, verbose_name='Slug')),
                ('excerpt', models.CharField(blank=True, default='', max_length=400, verbose_name='Résumé court')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('content_format', models.CharField(choices=[('text', 'Texte brut'), ('html', 'HTML riche')], default='text', max_length=10, verbose_name='Format du contenu')),
                ('announcement_date', models.DateField(blank=True, db_index=True, null=True, verbose_name="Date de l'annonce")),
                ('is_sunday_notice', models.BooleanField(db_default=False, default=False, verbose_name='annonce du dimanche')),
                ('sunday_date', models.DateField(blank=True, null=True, verbose_name='dimanche concerné')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='publication programmée')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmé'), ('published', 'Publié'), ('unpublished', 'Dépublié')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('unpublished_at', models.DateTimeField(blank=True, null=True, verbose_name='Dépublié le')),
                ('unpublish_reason', models.TextField(blank=True, default='', verbose_name='Motif de dépublication')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Icône')),
                ('color', models.CharField(blank=True, default='', max_length=7, verbose_name='Couleur hex')),
                ('display_order', models.IntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': "Catégorie d'article",
                'verbose_name_plural': "Catégories d'article",
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction_type', models.CharField(choices=[('pray', 'Je prie'), ('amen', 'Amen'), ('attend', 'Je participe')], db_index=True, max_length=20, verbose_name='Type de réaction')),
            ],
            options={
                'verbose_name': 'Réaction à un article',
                'verbose_name_plural': 'Réactions aux articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Lecture d'un article",
                'verbose_name_plural': "Lectures d'articles",
            },
        ),
    ]
