# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_initial'),
        ('hierarchy', '0002_initial'),
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_covers', to='files.file', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='article',
            name='scope_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='hierarchy.node', verbose_name='Nœud de portée'),
        ),
        migrations.AddField(
            model_name='article',
            name='scope_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='hierarchy.placeofworship', verbose_name='Lieu de culte'),
        ),
        migrations.AddField(
            model_name='article',
            name='unpublished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unpublished_articles', to=settings.AUTH_USER_MODEL, verbose_name='Dépublié par'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.articlecategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='articlereaction',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='news.article', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='articlereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='articleread',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='news.article'),
        ),
        migrations.AddField(
            model_name='articleread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='article_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='article_category_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['scope_node', 'status', '-published_at'], name='article_node_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(condition=models.Q(('is_sunday_notice', True)), fields=['sunday_date'], name='article_sunday_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(condition=models.Q(('status', 'scheduled')), fields=['publish_at'], name='article_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', '-created_at'], name='article_author_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_article_slug'),
        ),
        migrations.AddIndex(
            model_name='articlereaction',
            index=models.Index(fields=['article', 'reaction_type'], name='article_reaction_count_idx'),
        ),
        migrations.AddIndex(
            model_name='articlereaction',
            index=models.Index(fields=['user', 'article'], name='article_reaction_mine_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlereaction',
            constraint=models.UniqueConstraint(fields=('article', 'user', 'reaction_type'), name='unique_article_reaction_per_user_and_type'),
        ),
        migrations.AddIndex(
            model_name='articleread',
            index=models.Index(fields=['user', '-read_at'], name='article_read_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='articleread',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='unique_article_read_per_user'),
        ),
    ]
