# Generated by Django 5.2.16 on 2026-09-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='notify_followers',
            field=models.BooleanField(db_default=True, default=True, verbose_name='notifier les fidèles'),
        ),
    ]
