# Generated by Django 5.2.16 on 2026-09-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_notify_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image_alt',
            field=models.CharField(blank=True, db_default='', default='', max_length=250, verbose_name='texte alternatif de la bannière'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_decorative',
            field=models.BooleanField(db_default=False, default=False, verbose_name='bannière décorative'),
        ),
    ]
