# Generated by Django 5.2.16 on 2026-09-29 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
        ("hierarchy", "0014_v1_routes_capacites"),
        ("news", "0004_article_cover_image_alt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="pinned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="épinglé le"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="pinned_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="épinglé jusqu'au"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                condition=models.Q(("pinned_until__isnull", False)),
                fields=["pinned_until"],
                name="article_pinned_idx",
            ),
        ),
    ]
