# Generated by Django 5.2.7 on 2026-09-25 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
        ('hierarchy', '0006_seed_offices_catalogue'),
        ('news', '0008_articlereaction'),
        ('org', '0003_backfill_main_church'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Lecture d'un article",
                'verbose_name_plural': "Lectures d'articles",
            },
        ),
        migrations.AddField(
            model_name='article',
            name='is_sunday_notice',
            field=models.BooleanField(db_default=False, default=False, verbose_name='annonce du dimanche'),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publication programmée'),
        ),
        migrations.AddField(
            model_name='article',
            name='scope_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='hierarchy.node', verbose_name='Nœud de portée'),
        ),
        migrations.AddField(
            model_name='article',
            name='scope_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='hierarchy.placeofworship', verbose_name='Lieu de culte'),
        ),
        migrations.AddField(
            model_name='article',
            name='sunday_date',
            field=models.DateField(blank=True, null=True, verbose_name='dimanche concerné'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmé'), ('published', 'Publié'), ('unpublished', 'Dépublié')], db_index=True, default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['scope_node', 'status', '-published_at'], name='article_node_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(condition=models.Q(('is_sunday_notice', True)), fields=['sunday_date'], name='article_sunday_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(condition=models.Q(('status', 'scheduled')), fields=['publish_at'], name='article_scheduled_idx'),
        ),
        migrations.AddField(
            model_name='articleread',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='news.article'),
        ),
        migrations.AddField(
            model_name='articleread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='articleread',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='unique_article_read_per_user'),
        ),
    ]
