# Generated by Django 5.2.7 on 2026-09-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_article_read_user_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('announcement', 'Annonce'), ('article', 'Article'), ('pastoral_letter', 'Lettre Pastorale'), ('meditation', 'Méditation du jour')], db_index=True, default='article', max_length=20, verbose_name='Type de contenu'),
        ),
    ]
