# Generated by Django 5.2.7 on 2026-09-25 01:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=100, verbose_name='libellé')),
                ('is_territorial', models.BooleanField(default=True, verbose_name='territorial')),
                ('holds_registers', models.BooleanField(default=False, help_text="Reçoit les demandes d'actes (paroisse, quasi-paroisse).", verbose_name='tient des registres')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('allowed_parent_types', models.ManyToManyField(blank=True, related_name='allowed_child_types', to='hierarchy.nodetype', verbose_name='types de parents autorisés')),
            ],
            options={
                'verbose_name': 'type de nœud',
                'verbose_name_plural': 'types de nœuds',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='code')),
                ('status', models.CharField(choices=[('en_fondation', 'En fondation'), ('erige', 'Érigé'), ('supprime', 'Supprimé')], db_index=True, default='erige', max_length=20, verbose_name='statut')),
                ('address', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='ville')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('erected_at', models.DateField(blank=True, null=True, verbose_name="date d'érection")),
                ('is_active_on_platform', models.BooleanField(db_index=True, default=False, verbose_name='active sur Jàngu Bi')),
                ('legacy_model', models.CharField(blank=True, default='', max_length=40, verbose_name="modèle d'origine")),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, verbose_name="identifiant d'origine")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('located_in', models.ForeignKey(blank=True, help_text="Lien géographique d'un nœud non territorial (ex. communauté située dans un diocèse).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='located_nodes', to='hierarchy.node', verbose_name='situé dans')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='hierarchy.nodetype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'nœud',
                'verbose_name_plural': 'nœuds',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfWorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('kind', models.CharField(choices=[('eglise_paroissiale', 'Église paroissiale'), ('succursale', 'Succursale'), ('chapelle', 'Chapelle'), ('station', 'Station'), ('sanctuaire', 'Sanctuaire')], default='chapelle', max_length=30, verbose_name='type')),
                ('is_main', models.BooleanField(default=False, verbose_name='lieu principal')),
                ('address', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='ville')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name="identifiant d'origine (org.Church)")),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='hierarchy.node', verbose_name='nœud')),
            ],
            options={
                'verbose_name': 'lieu de culte',
                'verbose_name_plural': 'lieux de culte',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('messe', 'Messe'), ('confession', 'Confession'), ('adoration', 'Adoration')], default='messe', max_length=20, verbose_name='type')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour')),
                ('start_time', models.TimeField(verbose_name='début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='fin')),
                ('language', models.CharField(blank=True, default='fr', max_length=20, verbose_name='langue')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='note')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valable du')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name="valable jusqu'au")),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='hierarchy.placeofworship')),
            ],
            options={
                'verbose_name': 'horaire',
                'verbose_name_plural': 'horaires',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('kind', models.CharField(choices=[('messe', 'Messe'), ('confession', 'Confession'), ('adoration', 'Adoration')], default='messe', max_length=20, verbose_name='type')),
                ('cancelled', models.BooleanField(default=False, verbose_name='annulation')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='fin')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='note')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='hierarchy.placeofworship')),
            ],
            options={
                'verbose_name': "exception d'horaire",
                'verbose_name_plural': "exceptions d'horaire",
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['type', 'status'], name='hierarchy_node_type_status'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('legacy_model', 'legacy_id'), name='hierarchy_node_unique_legacy'),
        ),
        migrations.AddConstraint(
            model_name='placeofworship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('node',), name='hierarchy_place_unique_main_per_node'),
        ),
        migrations.AddConstraint(
            model_name='massschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='hierarchy_schedule_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='massschedule',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='hierarchy_schedule_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='massschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='hierarchy_schedule_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled', True), ('start_time__isnull', False), _connector='OR'), name='hierarchy_exception_extra_needs_time'),
        ),
    ]
