# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "événement d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('code', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='code')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('domain', models.CharField(max_length=40, verbose_name='domaine')),
            ],
            options={
                'verbose_name': 'capacité',
                'verbose_name_plural': 'capacités',
                'ordering': ['domain', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effect', models.CharField(choices=[('retrait', 'Retrait')], default='retrait', max_length=10)),
            ],
            options={
                'verbose_name': 'retrait de capacité',
                'verbose_name_plural': 'retraits de capacité',
            },
        ),
        migrations.CreateModel(
            name='MassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('messe', 'Messe'), ('confession', 'Confession'), ('adoration', 'Adoration')], default='messe', max_length=20, verbose_name='type')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour')),
                ('start_time', models.TimeField(verbose_name='début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='fin')),
                ('language', models.CharField(blank=True, default='fr', max_length=20, verbose_name='langue')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='note')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valable du')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name="valable jusqu'au")),
            ],
            options={
                'verbose_name': 'horaire',
                'verbose_name_plural': 'horaires',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='code')),
                ('status', models.CharField(choices=[('en_fondation', 'En fondation'), ('erige', 'Érigé'), ('supprime', 'Supprimé')], db_index=True, default='erige', max_length=20, verbose_name='statut')),
                ('address', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='ville')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('erected_at', models.DateField(blank=True, null=True, verbose_name="date d'érection")),
                ('is_active_on_platform', models.BooleanField(db_index=True, default=False, verbose_name='active sur Jàngu Bi')),
                ('legacy_model', models.CharField(blank=True, default='', max_length=40, verbose_name="modèle d'origine")),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, verbose_name="identifiant d'origine")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'nœud',
                'verbose_name_plural': 'nœuds',
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=100, verbose_name='libellé')),
                ('is_territorial', models.BooleanField(default=True, verbose_name='territorial')),
                ('holds_registers', models.BooleanField(default=False, help_text="Reçoit les demandes d'actes (paroisse, quasi-paroisse).", verbose_name='tient des registres')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'type de nœud',
                'verbose_name_plural': 'types de nœuds',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OfficeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('status', models.CharField(choices=[('proposee', 'Proposée'), ('active', 'Active'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], db_index=True, default='proposee', max_length=10, verbose_name='statut')),
                ('decree_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='référence du décret')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='note')),
            ],
            options={
                'verbose_name': 'nomination',
                'verbose_name_plural': 'nominations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('required_order', models.CharField(choices=[('aucun', 'Aucun'), ('diacre', 'Diacre'), ('pretre', 'Prêtre'), ('eveque', 'Évêque')], default='aucun', max_length=10, verbose_name='ordre requis')),
                ('cardinality', models.CharField(choices=[('one', 'Un seul titulaire'), ('many', 'Plusieurs titulaires')], default='many', max_length=4, verbose_name='titulaires')),
                ('appointed_by_platform', models.BooleanField(default=False, help_text='Nomination saisie par Numerisen (ex. évêque diocésain, nomination romaine).', verbose_name='nommé par la plateforme')),
                ('inherits_down', models.BooleanField(default=True, verbose_name='hérite sur le sous-arbre')),
                ('is_system', models.BooleanField(default=False, verbose_name='office du profil par défaut')),
            ],
            options={
                'verbose_name': "type d'office",
                'verbose_name_plural': "types d'office",
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='PlaceOfWorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('kind', models.CharField(choices=[('eglise_paroissiale', 'Église paroissiale'), ('succursale', 'Succursale'), ('chapelle', 'Chapelle'), ('station', 'Station'), ('sanctuaire', 'Sanctuaire')], default='chapelle', max_length=30, verbose_name='type')),
                ('is_main', models.BooleanField(default=False, verbose_name='lieu principal')),
                ('address', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='ville')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name="identifiant d'origine (org.Church)")),
            ],
            options={
                'verbose_name': 'lieu de culte',
                'verbose_name_plural': 'lieux de culte',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('kind', models.CharField(choices=[('messe', 'Messe'), ('confession', 'Confession'), ('adoration', 'Adoration')], default='messe', max_length=20, verbose_name='type')),
                ('cancelled', models.BooleanField(default=False, verbose_name='annulation')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='fin')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='note')),
            ],
            options={
                'verbose_name': "exception d'horaire",
                'verbose_name_plural': "exceptions d'horaire",
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
