# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_initial'),
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capabilityoverride',
            name='capability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='hierarchy.capability'),
        ),
        migrations.AddField(
            model_name='node',
            name='located_in',
            field=models.ForeignKey(blank=True, help_text="Lien géographique d'un nœud non territorial (ex. communauté située dans un diocèse).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='located_nodes', to='hierarchy.node', verbose_name='situé dans'),
        ),
        migrations.AddField(
            model_name='capabilityoverride',
            name='diocese_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to='hierarchy.node'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='hierarchy.node'),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='allowed_parent_types',
            field=models.ManyToManyField(blank=True, related_name='allowed_child_types', to='hierarchy.nodetype', verbose_name='types de parents autorisés'),
        ),
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='hierarchy.nodetype', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='officeassignment',
            name='appointed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_made', to=settings.AUTH_USER_MODEL, verbose_name='nommé par'),
        ),
        migrations.AddField(
            model_name='officeassignment',
            name='decree_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.file', verbose_name='décret'),
        ),
        migrations.AddField(
            model_name='officeassignment',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_assignments', to='hierarchy.node'),
        ),
        migrations.AddField(
            model_name='officeassignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_assignments', to=settings.AUTH_USER_MODEL, verbose_name='personne'),
        ),
        migrations.AddField(
            model_name='officetype',
            name='appointed_by',
            field=models.ManyToManyField(blank=True, related_name='can_appoint', to='hierarchy.officetype', verbose_name='nommé par'),
        ),
        migrations.AddField(
            model_name='officetype',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='office_types', to='hierarchy.capability'),
        ),
        migrations.AddField(
            model_name='officetype',
            name='node_types',
            field=models.ManyToManyField(related_name='office_types', to='hierarchy.nodetype', verbose_name="s'exerce sur"),
        ),
        migrations.AddField(
            model_name='officeassignment',
            name='office_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hierarchy.officetype'),
        ),
        migrations.AddField(
            model_name='capabilityoverride',
            name='office_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='hierarchy.officetype'),
        ),
        migrations.AddField(
            model_name='placeofworship',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='hierarchy.node', verbose_name='nœud'),
        ),
        migrations.AddField(
            model_name='massschedule',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='hierarchy.placeofworship'),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='hierarchy.placeofworship'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_type', 'target_id'], name='hierarchy_audit_target'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['node', '-at'], name='hierarchy_audit_node_at'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action'], name='hierarchy_audit_action_pattern', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['type', 'status'], name='hierarchy_node_type_status'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['path'], name='hierarchy_node_path_pattern', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('legacy_model', 'legacy_id'), name='hierarchy_node_unique_legacy'),
        ),
        migrations.AddIndex(
            model_name='officeassignment',
            index=models.Index(fields=['person', 'status'], name='hierarchy_assign_person_status'),
        ),
        migrations.AddIndex(
            model_name='officeassignment',
            index=models.Index(fields=['node', 'office_type', 'status'], name='hierarchy_assign_node_office'),
        ),
        migrations.AddIndex(
            model_name='officeassignment',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['person', 'start_date', 'end_date'], name='hierarchy_assign_active_person'),
        ),
        migrations.AddConstraint(
            model_name='officeassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='hierarchy_assignment_dates'),
        ),
        migrations.AddConstraint(
            model_name='capabilityoverride',
            constraint=models.UniqueConstraint(fields=('diocese_node', 'office_type', 'capability'), name='hierarchy_override_unique'),
        ),
        migrations.AddConstraint(
            model_name='placeofworship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('node',), name='hierarchy_place_unique_main_per_node'),
        ),
        migrations.AddConstraint(
            model_name='massschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='hierarchy_schedule_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='massschedule',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='hierarchy_schedule_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='massschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='hierarchy_schedule_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled', True), ('start_time__isnull', False), _connector='OR'), name='hierarchy_exception_extra_needs_time'),
        ),
    ]
