# Generated by Django 5.2.7 on 2026-09-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_migrate_org'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['path'], name='hierarchy_node_path_pattern', opclasses=['varchar_pattern_ops']),
        ),
    ]
