# Generated by Django 5.2.7 on 2026-09-25 02:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
        ('hierarchy', '0004_node_path_pattern_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('code', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='code')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('domain', models.CharField(max_length=40, verbose_name='domaine')),
            ],
            options={
                'verbose_name': 'capacité',
                'verbose_name_plural': 'capacités',
                'ordering': ['domain', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('required_order', models.CharField(choices=[('aucun', 'Aucun'), ('diacre', 'Diacre'), ('pretre', 'Prêtre'), ('eveque', 'Évêque')], default='aucun', max_length=10, verbose_name='ordre requis')),
                ('cardinality', models.CharField(choices=[('one', 'Un seul titulaire'), ('many', 'Plusieurs titulaires')], default='many', max_length=4, verbose_name='titulaires')),
                ('appointed_by_platform', models.BooleanField(default=False, help_text='Nomination saisie par Numerisen (ex. évêque diocésain, nomination romaine).', verbose_name='nommé par la plateforme')),
                ('inherits_down', models.BooleanField(default=True, verbose_name='hérite sur le sous-arbre')),
                ('is_system', models.BooleanField(default=False, verbose_name='office du profil par défaut')),
                ('appointed_by', models.ManyToManyField(blank=True, related_name='can_appoint', to='hierarchy.officetype', verbose_name='nommé par')),
                ('capabilities', models.ManyToManyField(blank=True, related_name='office_types', to='hierarchy.capability')),
                ('node_types', models.ManyToManyField(related_name='office_types', to='hierarchy.nodetype', verbose_name="s'exerce sur")),
            ],
            options={
                'verbose_name': "type d'office",
                'verbose_name_plural': "types d'office",
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='hierarchy.node')),
            ],
            options={
                'verbose_name': "événement d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='hierarchy_audit_target'), models.Index(fields=['node', '-at'], name='hierarchy_audit_node_at'), models.Index(fields=['action'], name='hierarchy_audit_action_pattern', opclasses=['varchar_pattern_ops'])],
            },
        ),
        migrations.CreateModel(
            name='OfficeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('status', models.CharField(choices=[('proposee', 'Proposée'), ('active', 'Active'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], db_index=True, default='proposee', max_length=10, verbose_name='statut')),
                ('decree_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='référence du décret')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='note')),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_made', to=settings.AUTH_USER_MODEL, verbose_name='nommé par')),
                ('decree_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.file', verbose_name='décret')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_assignments', to='hierarchy.node')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_assignments', to=settings.AUTH_USER_MODEL, verbose_name='personne')),
                ('office_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hierarchy.officetype')),
            ],
            options={
                'verbose_name': 'nomination',
                'verbose_name_plural': 'nominations',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['person', 'status'], name='hierarchy_assign_person_status'), models.Index(fields=['node', 'office_type', 'status'], name='hierarchy_assign_node_office'), models.Index(condition=models.Q(('status', 'active')), fields=['person', 'start_date', 'end_date'], name='hierarchy_assign_active_person')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='hierarchy_assignment_dates')],
            },
        ),
        migrations.CreateModel(
            name='CapabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effect', models.CharField(choices=[('retrait', 'Retrait')], default='retrait', max_length=10)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='hierarchy.capability')),
                ('diocese_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to='hierarchy.node')),
                ('office_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='hierarchy.officetype')),
            ],
            options={
                'verbose_name': 'retrait de capacité',
                'verbose_name_plural': 'retraits de capacité',
                'constraints': [models.UniqueConstraint(fields=('diocese_node', 'office_type', 'capability'), name='hierarchy_override_unique')],
            },
        ),
    ]
