# Generated by Django 5.2.7 on 2026-09-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_seed_offices_catalogue'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='node',
            name='hierarchy_node_unique_legacy',
        ),
        migrations.RemoveField(
            model_name='node',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='node',
            name='legacy_model',
        ),
        migrations.RemoveField(
            model_name='placeofworship',
            name='legacy_id',
        ),
    ]
