# Generated by Django 5.2.16 on 2026-09-25 22:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
        ('hierarchy', '0005_drop_legacy_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.file', verbose_name='fichier')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_attachments', to=settings.AUTH_USER_MODEL, verbose_name='personne')),
            ],
            options={
                'verbose_name': 'justificatif de déclaration',
                'verbose_name_plural': 'justificatifs de déclaration',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('person', 'file'), name='hierarchy_declaration_attachment_unique')],
            },
        ),
    ]
