# Generated by Django 5.2.16 on 2026-09-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0006_declaration_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='acts_delay_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='délai indicatif des actes (jours ouvrés)'),
        ),
        migrations.AddField(
            model_name='node',
            name='acts_welcome_message',
            field=models.TextField(blank=True, db_default='', default='', verbose_name="message d'accueil des demandes d'actes"),
        ),
        migrations.AddField(
            model_name='node',
            name='email',
            field=models.EmailField(blank=True, db_default='', default='', max_length=254, verbose_name='e-mail du secrétariat'),
        ),
        migrations.AddField(
            model_name='node',
            name='office_hours',
            field=models.JSONField(blank=True, db_default=[], default=list, help_text='Liste de créneaux : [{« days » : « Lun. – ven. », « hours » : « 9 h-12 h »}].', verbose_name="horaires d'accueil"),
        ),
        migrations.AddField(
            model_name='node',
            name='phone',
            field=models.CharField(blank=True, db_default='', default='', max_length=30, verbose_name='téléphone du secrétariat'),
        ),
        migrations.AddField(
            model_name='node',
            name='secretariat_public',
            field=models.BooleanField(db_default=False, default=False, help_text="Téléphone, e-mail et horaires d'accueil affichés sur la fiche publique.", verbose_name='secrétariat publié'),
        ),
    ]
