# Generated by Django 5.2.16 on 2026-09-26 07:30

from django.db import migrations, models

# Copie FIGÉE : une migration ne dépend pas du code applicatif (profiles.py évoluera).
CURE_QUALITIES = [
    {"code": "cure", "label": "Curé"},
    {"code": "administrateur", "label": "Administrateur paroissial"},
]


def seed_qualities(apps, schema_editor):
    OfficeType = apps.get_model("hierarchy", "OfficeType")
    OfficeAssignment = apps.get_model("hierarchy", "OfficeAssignment")
    OfficeType.objects.filter(code="cure", qualities=[]).update(qualities=CURE_QUALITIES)
    # Les nominations de curé existantes sont des nominations de curé.
    OfficeAssignment.objects.filter(office_type__code="cure", quality="").update(quality="cure")


def unseed_qualities(apps, schema_editor):
    # Les colonnes disparaissent au retour arrière : rien à défaire.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0007_node_secretariat'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeassignment',
            name='quality',
            field=models.CharField(blank=True, db_default='', default='', help_text="Code d'une qualité de l'office (ex. curé ou administrateur paroissial).", max_length=40, verbose_name='qualité'),
        ),
        migrations.AddField(
            model_name='officetype',
            name='qualities',
            field=models.JSONField(blank=True, db_default=[], default=list, help_text='Titres possibles du titulaire : [{« code » : « cure », « label » : « Curé »}, …]. La première est la qualité par défaut.', verbose_name='qualités'),
        ),
        migrations.RunPython(seed_qualities, unseed_qualities),
    ]
