# Generated by Django 5.2.16 on 2026-09-29 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0011_dons_voir_agregats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParishMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="paroisse principale"
                    ),
                ),
                ("joined_at", models.DateTimeField(verbose_name="membre depuis")),
                (
                    "removed_by_parish_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="retiré par la paroisse le"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="hierarchy.node",
                        verbose_name="paroisse",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="retiré par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parish_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="fidèle",
                    ),
                ),
            ],
            options={
                "verbose_name": "appartenance à une paroisse",
                "verbose_name_plural": "appartenances aux paroisses",
                "ordering": ["-is_primary", "joined_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("removed_by_parish_at__isnull", True)),
                        fields=["node", "joined_at"],
                        name="hierarchy_membership_active",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "node"), name="hierarchy_membership_unique"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_primary", True), ("removed_by_parish_at__isnull", True)
                        ),
                        fields=("user",),
                        name="hierarchy_membership_one_primary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_primary", False),
                            ("removed_by_parish_at__isnull", True),
                            _connector="OR",
                        ),
                        name="hierarchy_membership_removed_not_primary",
                    ),
                ],
            },
        ),
    ]
