# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reservee', 'Réservée'), ('annulee_fidele', 'Annulée par le fidèle'), ('annulee_pretre', 'Annulée par le prêtre'), ('honoree', 'Honorée'), ('absent', 'Absent')], db_index=True, default='reservee', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_message', models.CharField(blank=True, default='', max_length=300)),
                ('reminder_day_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_hours_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'réservation de confession',
                'verbose_name_plural': 'réservations de confession',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfessionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='début')),
                ('ends_at', models.DateTimeField(verbose_name='fin')),
                ('status', models.CharField(choices=[('libre', 'Libre'), ('reserve', 'Réservé'), ('bloque', 'Bloqué')], db_index=True, default='libre', max_length=10)),
            ],
            options={
                'verbose_name': 'créneau de confession',
                'verbose_name_plural': 'créneaux de confession',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfessionSlotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='jour (0 = lundi)')),
                ('start_time', models.TimeField(verbose_name='début')),
                ('end_time', models.TimeField(verbose_name='fin')),
                ('slot_minutes', models.PositiveSmallIntegerField(default=10, verbose_name="durée d'un créneau (minutes)")),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valable du')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name="valable jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'règle de créneaux',
                'verbose_name_plural': 'règles de créneaux',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
