# Generated by Django 5.2.7 on 2026-09-25 04:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0006_seed_offices_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessionSlotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='jour (0 = lundi)')),
                ('start_time', models.TimeField(verbose_name='début')),
                ('end_time', models.TimeField(verbose_name='fin')),
                ('slot_minutes', models.PositiveSmallIntegerField(default=10, verbose_name="durée d'un créneau (minutes)")),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valable du')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name="valable jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_rules', to='hierarchy.placeofworship')),
                ('priest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'règle de créneaux',
                'verbose_name_plural': 'règles de créneaux',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConfessionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='début')),
                ('ends_at', models.DateTimeField(verbose_name='fin')),
                ('status', models.CharField(choices=[('libre', 'Libre'), ('reserve', 'Réservé'), ('bloque', 'Bloqué')], db_index=True, default='libre', max_length=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_slots', to='hierarchy.placeofworship')),
                ('priest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_slots', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='confessions.confessionslotrule')),
            ],
            options={
                'verbose_name': 'créneau de confession',
                'verbose_name_plural': 'créneaux de confession',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reservee', 'Réservée'), ('annulee_fidele', 'Annulée par le fidèle'), ('annulee_pretre', 'Annulée par le prêtre'), ('honoree', 'Honorée'), ('absent', 'Absent')], db_index=True, default='reservee', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_message', models.CharField(blank=True, default='', max_length=300)),
                ('reminder_day_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_hours_sent_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='confessions.confessionslot')),
            ],
            options={
                'verbose_name': 'réservation de confession',
                'verbose_name_plural': 'réservations de confession',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['person', 'status'], name='confession_booking_person_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'reservee')), fields=('slot',), name='confession_booking_one_active_per_slot')],
            },
        ),
        migrations.AddConstraint(
            model_name='confessionslotrule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='confession_rule_times'),
        ),
        migrations.AddConstraint(
            model_name='confessionslotrule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='confession_rule_weekday'),
        ),
        migrations.AddConstraint(
            model_name='confessionslotrule',
            constraint=models.CheckConstraint(condition=models.Q(('slot_minutes__gte', 5), ('slot_minutes__lte', 60)), name='confession_rule_slot_minutes'),
        ),
        migrations.AddIndex(
            model_name='confessionslot',
            index=models.Index(fields=['place', 'status', 'starts_at'], name='confession_slot_place_idx'),
        ),
        migrations.AddConstraint(
            model_name='confessionslot',
            constraint=models.UniqueConstraint(fields=('priest', 'starts_at'), name='confession_slot_unique_priest_start'),
        ),
        migrations.AddConstraint(
            model_name='confessionslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='confession_slot_times'),
        ),
    ]
