# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confessions', '0001_initial'),
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confessionbooking',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confessionslot',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_slots', to='hierarchy.placeofworship'),
        ),
        migrations.AddField(
            model_name='confessionslot',
            name='priest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confessionbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='confessions.confessionslot'),
        ),
        migrations.AddField(
            model_name='confessionslotrule',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_rules', to='hierarchy.placeofworship'),
        ),
        migrations.AddField(
            model_name='confessionslotrule',
            name='priest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confessionslot',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='confessions.confessionslotrule'),
        ),
        migrations.AddIndex(
            model_name='confessionbooking',
            index=models.Index(fields=['person', 'status'], name='confession_booking_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='confessionbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reservee')), fields=('slot',), name='confession_booking_one_active_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='confessionslotrule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='confession_rule_times'),
        ),
        migrations.AddConstraint(
            model_name='confessionslotrule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='confession_rule_weekday'),
        ),
        migrations.AddConstraint(
            model_name='confessionslotrule',
            constraint=models.CheckConstraint(condition=models.Q(('slot_minutes__gte', 5), ('slot_minutes__lte', 60)), name='confession_rule_slot_minutes'),
        ),
        migrations.AddIndex(
            model_name='confessionslot',
            index=models.Index(fields=['place', 'status', 'starts_at'], name='confession_slot_place_idx'),
        ),
        migrations.AddConstraint(
            model_name='confessionslot',
            constraint=models.UniqueConstraint(fields=('priest', 'starts_at'), name='confession_slot_unique_priest_start'),
        ),
        migrations.AddConstraint(
            model_name='confessionslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='confession_slot_times'),
        ),
    ]
