# Generated by Django 5.2.7 on 2026-09-25 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0005_drop_legacy_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='nom complet')),
                ('fonction', models.CharField(choices=[('cure', 'Curé'), ('vicaire', 'Vicaire'), ('secretaire', 'Secrétaire paroissial'), ('referent_numerique', 'Référent numérique'), ('chancelier', 'Chancelier'), ('eveque', 'Évêque'), ('autre', 'Autre')], max_length=30, verbose_name='fonction')),
                ('paroisse', models.CharField(max_length=200, verbose_name='paroisse')),
                ('telephone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('message', models.TextField(blank=True, default='', max_length=1000, verbose_name='message')),
                ('consented_at', models.DateTimeField(verbose_name='consentement le')),
                ('cure_informe', models.BooleanField(default=False, verbose_name='curé informé')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='traitée le')),
                ('diocese_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation_requests', to='hierarchy.node', verbose_name='diocèse')),
            ],
            options={
                'verbose_name': 'demande de présentation',
                'verbose_name_plural': 'demandes de présentation',
                'ordering': ['-created_at'],
            },
        ),
    ]
