# Generated by Django 5.2.16 on 2026-09-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.CharField(max_length=64, verbose_name="lot")),
                ("seeder", models.CharField(max_length=64, verbose_name="semeur")),
                ("model", models.CharField(max_length=100, verbose_name="modèle")),
                (
                    "object_id",
                    models.CharField(max_length=64, verbose_name="identifiant"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "objet de données de test",
                "verbose_name_plural": "objets de données de test",
                "indexes": [
                    models.Index(
                        fields=["batch", "seeder", "model"],
                        name="core_seed_record_lookup",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "model", "object_id"),
                        name="core_seed_record_uniq",
                    )
                ],
            },
        ),
    ]
