# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('document_type', models.CharField(choices=[('baptism', 'Certificat de baptême'), ('first_communion', 'Attestation de première communion'), ('confirmation', 'Attestation de confirmation'), ('religious_marriage', 'Attestation de mariage religieux'), ('godparent', 'Attestation parrain / marraine'), ('other', 'Autre document')], db_index=True, max_length=30)),
                ('document_type_free', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(choices=[('religious_marriage', 'Mariage religieux'), ('godparent', 'Parrain / marraine'), ('catechism', 'Inscription catéchèse'), ('parish_file', 'Dossier paroissial'), ('personal', 'Usage personnel'), ('other', 'Autre')], max_length=30)),
                ('reason_free', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('under_verification', 'En vérification'), ('info_requested', 'Complément demandé'), ('ready_for_pickup', 'Prête à retirer'), ('collected', 'Retirée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], db_index=True, default='submitted', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('requester_last_name', models.CharField(max_length=100)),
                ('requester_first_names', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(max_length=254)),
                ('registered_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('registered_first_names', models.CharField(blank=True, default='', max_length=200)),
                ('father_last_name', models.CharField(max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('pickup_mode', models.CharField(choices=[('secretariat', 'Au secrétariat de la paroisse du sacrement'), ('transfer_to_followed_parish', 'Transmis à ma paroisse')], db_default='secretariat', default='secretariat', max_length=40)),
                ('pickup_hours', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('pickup_message', models.TextField(blank=True, db_default='', default='')),
                ('register_volume', models.CharField(blank=True, db_default='', default='', max_length=40)),
                ('register_page', models.CharField(blank=True, db_default='', default='', max_length=20)),
                ('register_number', models.CharField(blank=True, db_default='', default='', max_length=40)),
                ('register_marginal_notes', models.TextField(blank=True, db_default='', default='')),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('attachments_purged_at', models.DateTimeField(blank=True, null=True)),
                ('sacrament_approximate_date', models.CharField(max_length=20)),
                ('sacrament_location', models.CharField(max_length=200)),
                ('additional_info', models.TextField(blank=True, default='')),
                ('document_details', models.JSONField(blank=True, default=dict)),
                ('consent_given', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Demande de document',
                'verbose_name_plural': 'Demandes de documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(choices=[('user_supporting', 'Justificatif fidèle'), ('parish_final', 'Document final paroisse')], default='user_supporting', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequestStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Journal de statut',
                'verbose_name_plural': 'Journaux de statut',
            },
        ),
        migrations.CreateModel(
            name='DocumentSlaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalate_days', models.PositiveSmallIntegerField(default=7, verbose_name='relance de la paroisse (jours)')),
                ('requester_reminder_days', models.PositiveSmallIntegerField(default=5, verbose_name='relance du fidèle (jours)')),
                ('pickup_reminder_days', models.PositiveSmallIntegerField(default=3, verbose_name='rappel de retrait (jours)')),
            ],
            options={
                'verbose_name': 'Délais de traitement',
                'verbose_name_plural': 'Délais de traitement',
            },
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Note interne',
                'verbose_name_plural': 'Notes internes',
            },
        ),
    ]
