# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('files', '0001_initial'),
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_document_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='pickup_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarchy.placeofworship'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to='hierarchy.node', verbose_name='paroisse du sacrement'),
        ),
        migrations.AddField(
            model_name='documentrequestattachment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_request_attachments', to='files.file'),
        ),
        migrations.AddField(
            model_name='documentrequestattachment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.documentrequest'),
        ),
        migrations.AddField(
            model_name='documentrequestattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequeststatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequeststatuslog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='documents.documentrequest'),
        ),
        migrations.AddField(
            model_name='documentslasetting',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_sla', to='hierarchy.node'),
        ),
        migrations.AddField(
            model_name='internalnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_internal_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalnote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='documents.documentrequest'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['requester', '-created_at'], name='docreq_requester_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['status', '-created_at'], name='docreq_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['document_type', 'status'], name='docreq_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['target_node', 'status', '-created_at'], name='docreq_node_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequeststatuslog',
            index=models.Index(fields=['request', 'created_at'], name='doclog_request_idx'),
        ),
    ]
