# Generated by Django 5.2.16 on 2026-09-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentslasetting',
            name='indicative_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='délai indicatif annoncé au fidèle (jours)'),
        ),
    ]
