# Generated by Django 5.2.16 on 2026-09-26 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_sla_indicative_days'),
        ('hierarchy', '0007_node_secretariat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('baptism', 'Certificat de baptême'), ('first_communion', 'Attestation de première communion'), ('confirmation', 'Attestation de confirmation'), ('religious_marriage', 'Attestation de mariage religieux'), ('godparent', 'Attestation parrain / marraine'), ('other', 'Autre document')], max_length=30, verbose_name="type d'acte")),
                ('days', models.PositiveSmallIntegerField(verbose_name='délai indicatif (jours ouvrés)')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type_delays', to='hierarchy.node')),
            ],
            options={
                'verbose_name': "Délai par type d'acte",
                'verbose_name_plural': "Délais par type d'acte",
                'constraints': [models.UniqueConstraint(fields=('node', 'document_type'), name='documents_type_delay_node_type_uniq'), models.CheckConstraint(condition=models.Q(('days__gte', 1)), name='documents_type_delay_days_positive')],
            },
        ),
    ]
