# Generated by Django 5.2.7 on 2026-09-25 03:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentrequest_document_type_free'),
        ('hierarchy', '0006_seed_offices_catalogue'),
        ('org', '0003_backfill_main_church'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSlaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalate_days', models.PositiveSmallIntegerField(default=7, verbose_name='relance de la paroisse (jours)')),
                ('requester_reminder_days', models.PositiveSmallIntegerField(default=5, verbose_name='relance du fidèle (jours)')),
                ('pickup_reminder_days', models.PositiveSmallIntegerField(default=3, verbose_name='rappel de retrait (jours)')),
            ],
            options={
                'verbose_name': 'Délais de traitement',
                'verbose_name_plural': 'Délais de traitement',
            },
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='attachments_purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='pickup_hours',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='pickup_message',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='pickup_mode',
            field=models.CharField(choices=[('secretariat', 'Au secrétariat de la paroisse du sacrement'), ('transfer_to_followed_parish', 'Transmis à ma paroisse')], db_default='secretariat', default='secretariat', max_length=40),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='pickup_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarchy.placeofworship'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='register_marginal_notes',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='register_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=40),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='register_page',
            field=models.CharField(blank=True, db_default='', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='register_volume',
            field=models.CharField(blank=True, db_default='', default='', max_length=40),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='target_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to='hierarchy.node', verbose_name='paroisse du sacrement'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Soumise'), ('under_verification', 'En vérification'), ('info_requested', 'Complément demandé'), ('ready_for_pickup', 'Prête à retirer'), ('collected', 'Retirée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée'), ('validated', 'Validée (historique)'), ('document_deposited', 'Document déposé (historique)')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['target_node', 'status', '-created_at'], name='docreq_node_status_idx'),
        ),
        migrations.AddField(
            model_name='documentslasetting',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_sla', to='hierarchy.node'),
        ),
    ]
