"""Sonothèque : table partitionnée des événements d'écoute et configuration de recherche.

1. ``fr_unaccent`` : configuration plein texte française sans accents (unaccent + french_stem),
   créée seulement si elle n'existe pas (une autre app peut la partager).
2. ``audio_play_event`` : partitionnée par mois (``PARTITION BY RANGE (occurred_at)``, plan §3.6).
   - clé primaire ``(id, occurred_at)`` : la clé de partition doit figurer dans toute contrainte
     unique d'une table partitionnée ;
   - idempotence : index unique ``(client_event_id, occurred_at)`` ; le client renvoie le même
     couple lors d'une reprise, l'insertion se fait en ``ON CONFLICT DO NOTHING`` ;
   - **pas de clé étrangère** : un ``TRUNCATE`` des tables Django (tests transactionnels, flush)
     échouerait sur une table non gérée qui les référence. Les jointures vers ``audio_track`` ignorent
     les événements orphelins ; la purge à 13 mois les supprime ;
   - partition ``DEFAULT`` : filet de sécurité si la tâche mensuelle n'est pas passée ;
   - partitions du mois courant et des deux suivants créées ici ; ensuite par
     ``audio_play_event_partitions_task`` (le 1er de chaque mois, idempotente).
   Retour arrière : ``DROP TABLE`` (données d'écoute brutes perdues, c'est voulu).
"""

from django.db import migrations

FR_UNACCENT = """
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = 'fr_unaccent') THEN
        CREATE TEXT SEARCH CONFIGURATION fr_unaccent (COPY = french);
        ALTER TEXT SEARCH CONFIGURATION fr_unaccent
            ALTER MAPPING FOR hword, hword_part, word WITH unaccent, french_stem;
    END IF;
END
$$;
"""

PLAY_EVENT = """
CREATE TABLE audio_play_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    occurred_at timestamptz NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),
    client_event_id uuid NOT NULL,
    user_id uuid NULL,
    track_id uuid NOT NULL,
    kind varchar(10) NOT NULL,
    position_seconds double precision NOT NULL DEFAULT 0,
    device_id varchar(100) NOT NULL DEFAULT '',
    CONSTRAINT audio_play_event_pk PRIMARY KEY (id, occurred_at),
    CONSTRAINT audio_play_event_client_uniq UNIQUE (client_event_id, occurred_at)
) PARTITION BY RANGE (occurred_at);

CREATE INDEX audio_play_event_user_idx ON audio_play_event (user_id, occurred_at);
CREATE INDEX audio_play_event_track_idx ON audio_play_event (track_id, occurred_at);

CREATE TABLE audio_play_event_default PARTITION OF audio_play_event DEFAULT;

DO $$
DECLARE
    m date := date_trunc('month', now())::date;
    i int;
BEGIN
    FOR i IN 0..2 LOOP
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF audio_play_event FOR VALUES FROM (%L) TO (%L)',
            'audio_play_event_p' || to_char(m + make_interval(months => i), 'YYYYMM'),
            m + make_interval(months => i),
            m + make_interval(months => i + 1)
        );
    END LOOP;
END
$$;
"""


class Migration(migrations.Migration):
    dependencies = [("audio", "0001_initial")]

    operations = [
        migrations.RunSQL(FR_UNACCENT, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(PLAY_EVENT, reverse_sql="DROP TABLE IF EXISTS audio_play_event CASCADE;"),
    ]
