# Generated by Django 5.2.16 on 2026-09-29 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0002_play_event_partitioned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="hidden_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="retiré par la modération le"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="encoding_percent",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="avancement de l'encodage (%)"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="encoding_step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("analyse", "Analyse du fichier"),
                    ("normalisation", "Normalisation du volume"),
                    ("qualites", "Encodage des qualités"),
                    ("forme_onde", "Forme d'onde et dépôt"),
                    ("termine", "Terminé"),
                ],
                default="",
                max_length=16,
                verbose_name="étape de l'encodage",
            ),
        ),
        migrations.AddField(
            model_name="trackreport",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="audio.album",
            ),
        ),
        migrations.AlterField(
            model_name="trackreport",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="audio.track",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("track__isnull", False), ("album__isnull", True)),
                    models.Q(("track__isnull", True), ("album__isnull", False)),
                    _connector="OR",
                ),
                name="audio_report_track_xor_album",
            ),
        ),
    ]
