# Generated by Django 5.2.16 on 2026-09-29 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0003_staff_progression_pochette_signalement_album"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="trackreport",
            name="audio_report_track_xor_album",
        ),
        migrations.AddField(
            model_name="audiosource",
            name="hidden_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="retirée par la modération le"
            ),
        ),
        migrations.AddField(
            model_name="trackreport",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="audio.audiosource",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("track__isnull", False),
                        ("album__isnull", True),
                        ("source__isnull", True),
                    ),
                    models.Q(
                        ("track__isnull", True),
                        ("album__isnull", False),
                        ("source__isnull", True),
                    ),
                    models.Q(
                        ("track__isnull", True),
                        ("album__isnull", True),
                        ("source__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="audio_report_one_target",
            ),
        ),
    ]
