# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='adresse email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, unique=True, verbose_name='numéro de téléphone')),
                ('is_verified', models.BooleanField(default=False, help_text="L'utilisateur a validé son adresse email.", verbose_name='email vérifié')),
                ('is_active', models.BooleanField(default=False, help_text='Désactivez plutôt que de supprimer le compte.', verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, help_text="Accès à l'interface d'administration Django.", verbose_name='membre du staff')),
                ('keycloak_sub', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='identifiant Keycloak')),
                ('etat_de_vie', models.CharField(choices=[('laic', 'Laïc'), ('clerc', 'Clerc'), ('consacre', 'Consacré')], db_default='laic', default='laic', max_length=10, verbose_name='état de vie')),
                ('degre_ordre', models.CharField(choices=[('aucun', 'Aucun'), ('diacre_transitoire', 'Diacre (transitoire)'), ('diacre_permanent', 'Diacre permanent'), ('pretre', 'Prêtre'), ('eveque', 'Évêque')], db_default='aucun', default='aucun', max_length=20, verbose_name="degré d'ordre")),
                ('statut_verification', models.CharField(choices=[('declare', 'Déclaré'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], db_default='declare', default='declare', max_length=10, verbose_name='statut de vérification')),
                ('verification_note', models.CharField(blank=True, db_default='', default='', max_length=255, verbose_name='note de vérification')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='vérifié le')),
                ('consent_version', models.CharField(blank=True, db_default='', default='', max_length=20, verbose_name='version du consentement')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='consentement le')),
                ('last_seen_on', models.DateField(blank=True, null=True, verbose_name='dernière activité le')),
                ('last_mfa_on', models.DateField(blank=True, null=True, verbose_name='dernière connexion MFA le')),
                ('groups', models.ManyToManyField(blank=True, related_name='baseuser_set', to='auth.group', verbose_name='groupes')),
                ('incardination_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incardinated_people', to='hierarchy.node', verbose_name='incardination')),
                ('institut_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consecrated_members', to='hierarchy.node', verbose_name='institut')),
                ('paroisse_suivie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followers', to='hierarchy.node', verbose_name='paroisse suivie')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='baseuser_permissions_set', to='auth.permission', verbose_name='permissions')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='vérifié par')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=50, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, verbose_name='nom')),
                ('title', models.CharField(blank=True, choices=[('MR', 'M.'), ('MRS', 'Mme')], default='', max_length=10, verbose_name='civilité')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
            },
        ),
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(condition=models.Q(('etat_de_vie', 'laic'), _negated=True), fields=['statut_verification'], name='users_verification_queue'),
        ),
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(fields=['last_seen_on'], name='users_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(fields=['last_mfa_on'], name='users_last_mfa_idx'),
        ),
    ]
