# Generated by Django 5.2.16 on 2026-09-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='declared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='déclaré le'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='statut_verification',
            field=models.CharField(choices=[('declare', 'Déclaré'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté'), ('complement', 'Complément demandé')], db_default='declare', default='declare', max_length=10, verbose_name='statut de vérification'),
        ),
    ]
