# Generated by Django 5.2.16 on 2026-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_declaration_complement"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="vu à"),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="montrer_presence",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="montrer ma présence"
            ),
        ),
    ]
