# Generated by Django 5.2.16 on 2026-09-29 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0015_comptes_gerer"),
        ("users", "0003_presence"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeycloakEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        verbose_name="identifiant de l'événement",
                    ),
                ),
                ("event_type", models.CharField(max_length=80, verbose_name="type")),
                (
                    "keycloak_user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="compte Keycloak",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recu", "Reçu"),
                            ("traite", "Traité"),
                            ("ignore", "Ignoré"),
                            ("echec", "Échec"),
                        ],
                        db_index=True,
                        default="recu",
                        max_length=10,
                    ),
                ),
                ("result", models.CharField(blank=True, default="", max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "événement Keycloak",
                "verbose_name_plural": "événements Keycloak",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="KeycloakSyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("last_event_ms", models.BigIntegerField(default=0)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name": "curseur des événements Keycloak",
                "verbose_name_plural": "curseurs des événements Keycloak",
            },
        ),
        migrations.AddField(
            model_name="baseuser",
            name="admin_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administered_accounts",
                to="hierarchy.node",
                verbose_name="nœud gestionnaire du compte",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="keycloak_platform_admin",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="administrateur plateforme (Keycloak)",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="keycloak_sync_error",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=64,
                verbose_name="écart de synchronisation",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="keycloak_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="synchronisé avec Keycloak le"
            ),
        ),
        migrations.CreateModel(
            name="KeycloakSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("dry_run", models.BooleanField(default=True)),
                ("trigger", models.CharField(default="tache", max_length=20)),
                ("success", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("report", models.JSONField(blank=True, default=list)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "réconciliation Keycloak",
                "verbose_name_plural": "réconciliations Keycloak",
                "ordering": ["-started_at"],
            },
        ),
    ]
