# Generated by Django 5.2.7 on 2026-09-25 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0005_offices_capabilities_audit'),
        ('users', '0010_clergy_self_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='consentement le'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='consent_version',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='version du consentement'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='degre_ordre',
            field=models.CharField(choices=[('aucun', 'Aucun'), ('diacre_transitoire', 'Diacre (transitoire)'), ('diacre_permanent', 'Diacre permanent'), ('pretre', 'Prêtre'), ('eveque', 'Évêque')], default='aucun', max_length=20, verbose_name="degré d'ordre"),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='etat_de_vie',
            field=models.CharField(choices=[('laic', 'Laïc'), ('clerc', 'Clerc'), ('consacre', 'Consacré')], default='laic', max_length=10, verbose_name='état de vie'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='incardination_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incardinated_people', to='hierarchy.node', verbose_name='incardination'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='institut_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consecrated_members', to='hierarchy.node', verbose_name='institut'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='keycloak_sub',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='identifiant Keycloak'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='paroisse_suivie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followers', to='hierarchy.node', verbose_name='paroisse suivie'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='statut_verification',
            field=models.CharField(choices=[('declare', 'Déclaré'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], db_index=True, default='declare', max_length=10, verbose_name='statut de vérification'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='verification_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='note de vérification'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='vérifié le'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='vérifié par'),
        ),
    ]
