# Generated by Django 5.2.7 on 2026-09-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_phone_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='last_mfa_on',
            field=models.DateField(blank=True, null=True, verbose_name='dernière connexion MFA le'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_seen_on',
            field=models.DateField(blank=True, null=True, verbose_name='dernière activité le'),
        ),
    ]
