# Generated by Django 5.2.7 on 2026-09-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_person_activity_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='jwt_key',
        ),
    ]
