# Generated by Django 5.2.7 on 2026-09-25 08:53

import apps.rosary.storage
import django.contrib.postgres.search
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityRosary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intention', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], db_index=True, default='active', max_length=20)),
                ('current_decade', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chapelet communautaire',
                'verbose_name_plural': 'Chapelets communautaires',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('meditation', models.TextField(blank=True, help_text='Scripture reading or meditation for the mystery', null=True)),
                ('meditation_source', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('audio_file', models.FileField(blank=True, null=True, storage=apps.rosary.storage.RosaryAudioStorage(), upload_to='')),
                ('audio_duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
            ],
            options={
                'verbose_name_plural': 'Mysteries',
            },
        ),
        migrations.CreateModel(
            name='MysteryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('audio_file', models.FileField(blank=True, null=True, storage=apps.rosary.storage.RosaryAudioStorage(), upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MysteryPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SIGN_OF_CROSS', 'Sign of Cross'), ('CREED', 'Apostles Creed'), ('OUR_FATHER', 'Our Father'), ('HAIL_MARY', 'Hail Mary'), ('GLORY_BE', 'Glory Be'), ('FATIMA', 'Fatima Prayer'), ('HOLY_QUEEN', 'Hail Holy Queen'), ('FINAL_PRAYER', 'Final Prayer'), ('OTHER', 'Other')], max_length=50)),
                ('text', models.TextField()),
                ('language', models.CharField(default='FR', max_length=10)),
                ('source', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('tsv', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RosaryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RosaryIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Intention chapelet',
                'verbose_name_plural': 'Intentions chapelet',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RosaryParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participant chapelet',
                'verbose_name_plural': 'Participants chapelet',
            },
        ),
    ]
