# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rosary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityrosary',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_rosaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mystery',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysteries', to='rosary.mysterygroup'),
        ),
        migrations.AddField(
            model_name='communityrosary',
            name='mystery_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community_sessions', to='rosary.mysterygroup'),
        ),
        migrations.AddField(
            model_name='mysteryprayer',
            name='mystery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='rosary.mystery'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['type'], name='rosary_pray_type_e64e99_idx'),
        ),
        migrations.AddField(
            model_name='mysteryprayer',
            name='prayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysteries', to='rosary.prayer'),
        ),
        migrations.AddField(
            model_name='rosaryday',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='rosary.mysterygroup'),
        ),
        migrations.AddField(
            model_name='rosaryintention',
            name='rosary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentions', to='rosary.communityrosary'),
        ),
        migrations.AddField(
            model_name='rosaryintention',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_rosary_intentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rosaryparticipant',
            name='rosary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rosary.communityrosary'),
        ),
        migrations.AddField(
            model_name='rosaryparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosary_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mystery',
            constraint=models.UniqueConstraint(fields=('group', 'order'), name='unique_mystery_order_per_group'),
        ),
        migrations.AddConstraint(
            model_name='mysteryprayer',
            constraint=models.UniqueConstraint(fields=('mystery', 'order'), name='unique_prayer_order_per_mystery'),
        ),
        migrations.AlterUniqueTogether(
            name='rosaryparticipant',
            unique_together={('rosary', 'user')},
        ),
    ]
