# Generated by Django 5.2.16 on 2026-09-25 22:33

from django.db import migrations, models


# Fruit de chaque mystère (formulation usuelle française), pour les bases déjà peuplées par
# seed_rosary. Copie figée : la migration ne dépend pas du fichier d'amorçage.
FRUITS = {
    "joyeux": [
        "L'humilité",
        "La charité envers le prochain",
        "L'esprit de pauvreté",
        "L'obéissance et la pureté",
        "La recherche de Dieu en toutes choses",
    ],
    "lumineux": [
        "La fidélité aux promesses du baptême",
        "La confiance en Marie",
        "La conversion du cœur",
        "Le désir de la sainteté",
        "L'amour de l'Eucharistie",
    ],
    "douloureux": [
        "La contrition de nos péchés",
        "La pureté et la mortification",
        "Le courage face au mépris du monde",
        "La patience dans les épreuves",
        "Le don de soi et le salut des âmes",
    ],
    "glorieux": [
        "La foi",
        "L'espérance et le désir du Ciel",
        "L'ouverture aux dons du Saint-Esprit",
        "La grâce d'une bonne mort",
        "La confiance en Marie et la persévérance",
    ],
}


def fruits_fill(apps, schema_editor):
    Mystery = apps.get_model("rosary", "Mystery")
    for mystery in Mystery.objects.select_related("group").filter(fruit=""):
        fruits = FRUITS.get(mystery.group.slug.lower()) or FRUITS.get(mystery.group.name.lower())
        if fruits and 1 <= mystery.order <= len(fruits):
            mystery.fruit = fruits[mystery.order - 1]
            mystery.save(update_fields=["fruit"])


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystery',
            name='fruit',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='type',
            field=models.CharField(choices=[('SIGN_OF_CROSS', 'Signe de la croix'), ('CREED', 'Je crois en Dieu'), ('OUR_FATHER', 'Notre Père'), ('HAIL_MARY', 'Je vous salue Marie'), ('GLORY_BE', 'Gloire au Père'), ('FATIMA', 'Prière de Fatima'), ('HOLY_QUEEN', 'Salve Regina'), ('FINAL_PRAYER', 'Prière finale'), ('OTHER', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rosaryday',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True),
        ),
        migrations.RunPython(fruits_fill, migrations.RunPython.noop),
    ]
