# Generated by Django 5.2.7 on 2026-09-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0002_communityrosary_rosaryintention_rosaryparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystery',
            name='meditation_source',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prayer',
            name='source',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
    ]
