SPECTACULAR_SETTINGS = {
    'TITLE': 'JanguBi API',
    'DESCRIPTION': 'API for JanguBi',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Noms stables des énumérations de la V1 (sinon drf-spectacular suffixe au hasard
    # les collisions « status », « kind »… et le client généré change à chaque lot).
    'ENUM_NAME_OVERRIDES': {
        'NodeStatusEnum': 'apps.hierarchy.enums.NodeStatus',
        'ReadingEventKindEnum': 'apps.bible.models.ReadingEvent.Kind',
        'BookmarkColorEnum': 'apps.bible.models.Bookmark.Color',
        'PlaceKindEnum': 'apps.hierarchy.enums.PlaceKind',
        'ScheduleKindEnum': 'apps.hierarchy.enums.ScheduleKind',
        'WeekdayEnum': 'apps.hierarchy.enums.Weekday',
        'AssignmentStatusEnum': 'apps.hierarchy.enums.AssignmentStatus',
        'EtatDeVieEnum': 'apps.hierarchy.enums.EtatDeVie',
        'DegreOrdreEnum': 'apps.hierarchy.enums.DegreOrdre',
        'RequiredOrderEnum': 'apps.hierarchy.enums.RequiredOrder',
        'CardinalityEnum': 'apps.hierarchy.enums.Cardinality',
        'ArticleStatusEnum': 'apps.news.models.Article.Status',
        'DocumentTypeEnum': 'apps.documents.models.DocumentRequest.DocumentType',
        'ArticleContentTypeEnum': 'apps.news.models.Article.ContentType',
        'DocumentRequestStatusEnum': 'apps.documents.models.DocumentRequest.Status',
        'PickupModeEnum': 'apps.documents.models.DocumentRequest.PickupMode',
        'EventTypeEnum': 'apps.agenda.models.Event.EventType',
        'ContactFonctionEnum': 'apps.contact.enums.Fonction',
        'AccountRealmRoleEnum': 'apps.users.selectors_accounts.ROLES',
        'AccountStatusEnum': 'apps.users.selectors_accounts.STATUSES',
        'AccountMfaEnum': 'apps.users.apis_accounts.MFA_CHOICES',
        'FundKindEnum': 'apps.donations.enums.FundKind',
        'ParishFundKindEnum': 'apps.donations.serializers.PARISH_KINDS',
        'FundStatusEnum': 'apps.donations.enums.FundStatus',
        'FundDestinationEnum': 'apps.donations.enums.FundDestination',
        'DonationStatusEnum': 'apps.donations.enums.DonationStatus',
        'DonationChannelEnum': 'apps.donations.enums.DonationChannel',
        'PaymentMethodEnum': 'apps.donations.enums.PaymentMethod',
        'CashCollectionStatusEnum': 'apps.donations.enums.CashCollectionStatus',
        'PayoutStatusEnum': 'apps.donations.enums.PayoutStatus',
        'ReconciliationIssueKindEnum': 'apps.donations.serializers.ISSUE_KINDS',
        'ExportFileEnum': 'apps.donations.serializers.EXPORT_FILES',
        # Sonothèque (plan suite V2, §5).
        'AudioSourceKindEnum': 'apps.audio.enums.SourceKind',
        'AudioAlbumKindEnum': 'apps.audio.enums.AlbumKind',
        'AudioVisibilityEnum': 'apps.audio.enums.Visibility',
        'AudioTrackStatusEnum': 'apps.audio.enums.TrackStatus',
        'AudioLanguageEnum': 'apps.audio.enums.Language',
        'AudioLiturgicalSeasonEnum': 'apps.audio.enums.LiturgicalSeason',
        'AudioPlayEventKindEnum': 'apps.audio.enums.PlayEventKind',
        'AudioReportReasonEnum': 'apps.audio.enums.ReportReason',
        'AudioReportStatusEnum': 'apps.audio.enums.ReportStatus',
        'AudioReportDecisionEnum': 'apps.audio.serializers.REPORT_DECISIONS',
    },
}
