# Generated by Django 5.2.7 on 2026-09-25 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('event_type', models.CharField(choices=[('mass', 'Messe'), ('conference', 'Conférence'), ('retreat', 'Retraite'), ('ordination', 'Ordination'), ('other', 'Autre')], db_index=True, default='other', max_length=20, verbose_name='type')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='début')),
                ('end_at', models.DateTimeField(verbose_name='fin')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='lieu')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='rappel envoyé le')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='annulé le')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscription événement',
                'verbose_name_plural': 'Inscriptions événements',
            },
        ),
    ]
