# Generated by Django 5.2.16 on 2026-09-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='clôture des inscriptions'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='note',
            field=models.CharField(blank=True, db_default='', default='', max_length=300, verbose_name='remarque'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='seats',
            field=models.PositiveSmallIntegerField(db_default=1, default=1, verbose_name='nombre de personnes'),
        ),
    ]
