# Generated by Django 5.2.7 on 2026-09-25 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_event_cancelled_at_event_cancelled_by'),
        ('hierarchy', '0006_seed_offices_catalogue'),
        ('org', '0003_backfill_main_church'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rappel envoyé le'),
        ),
        migrations.AddField(
            model_name='event',
            name='scope_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hierarchy.node', verbose_name='nœud de portée'),
        ),
        migrations.AddField(
            model_name='event',
            name='scope_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hierarchy.placeofworship', verbose_name='lieu de culte'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['scope_node', 'start_at'], name='event_node_start_idx'),
        ),
    ]
